# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a588b5558a2cea397bf2da79905023679438b133bb42b0fdc5feee7cfc6fbacb300567a56f0e86356421c69e539ca522bea25f3d55eee013ef260a300a1b1d9

test:
  secret_key_base: c6d85c025c9902252b4626c6b4fc0ba6a0d6cbab219d600f01edf91c12974f9d6ec09bf61637482cd21153f5c31109540a478ef1442e5c4125c475ac11741cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
